submodule (caesar_plot_harmonic_convergence_module) caesar_plot_harmonic_convergence_submodule
  use caesar_dft_module
contains

module procedure plot_harmonic_convergence_mode
  output%mode_name = 'plot_harmonic_convergence'
  output%description = 'plots the harmonic convergence data generated by &
     &converge_harmonic_frequencies.'
  output%keywords = [                                                      &
     & KeywordData( 'python_path',                                         &
     &              'python_path is the path to the Python 3 executable.', &
     &              default_value='python3') ]
  output%main_subroutine => plot_harmonic_convergence_subroutine
  output%suppress_settings_file = .true.
end procedure

module procedure plot_harmonic_convergence_subroutine
  type(String) :: python_path
  
  python_path = arguments%value('python_path')
  
  call execute_python(str('plot_harmonic_convergence.py'),python_path)
end procedure
end submodule
