! ======================================================================
! Plots the phonon density of states and dispersion calculated by
!    calculate_harmonic_observables or calculate_anharmonic_observables.
! ======================================================================
module plot_harmonic_convergence_module
  use common_module
  implicit none
  
  private
  
  public :: plot_harmonic_convergence
contains

! ----------------------------------------------------------------------
! Generates keywords and helptext.
! ----------------------------------------------------------------------
function plot_harmonic_convergence() result(output)
  implicit none
  
  type(CaesarMode) :: output
  
  output%mode_name = 'plot_harmonic_convergence'
  output%description = 'plots the harmonic convergence data generated by &
     &converge_harmonic_frequencies.'
  output%keywords = [                                                      &
     & KeywordData( 'python_path',                                         &
     &              'python_path is the path to the Python 3 executable.', &
     &              default_value='python3') ]
  output%main_subroutine => plot_harmonic_convergence_subroutine
  output%suppress_settings_file = .true.
end function

! ----------------------------------------------------------------------
! Main program.
! ----------------------------------------------------------------------
subroutine plot_harmonic_convergence_subroutine(arguments)
  implicit none
  
  type(Dictionary), intent(in) :: arguments
  
  type(String) :: python_path
  
  python_path = arguments%value('python_path')
  
  call execute_python(str('plot_harmonic_convergence.py'),python_path)
end subroutine
end module
